#!/bin/bash

echo "🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥"
echo "💥 MEGA BATERIA DE TESTES - FESP-AI 💥"
echo "🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥"
echo ""

test_query() {
    echo "┃ 💬 $1"
    echo "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    response=$(curl -s -X POST "http://localhost:8000/chat" -H "Content-Type: application/json" -d "{\"message\": \"$1\"}" | jq -r '.response' | head -c 500)
    echo "📌 $response..."
    echo ""
    sleep 1
}

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  🎯 CONVERSA 1: Aluno querendo fazer TCC em IA       ║"
echo "╚══════════════════════════════════════════════════════╝"
test_query "Quero fazer TCC na área de IA, quais professores posso procurar?"
test_query "Qual o email do Elbert Macau?"
test_query "Quais disciplinas ele leciona?"
test_query "E a Lilian Berton trabalha com o quê?"

echo "╔══════════════════════════════════════════════════════╗"
echo "║  🎯 CONVERSA 2: Planejando grade horária             ║"
echo "╚══════════════════════════════════════════════════════╝"
test_query "Quero cursar Inteligência Artificial, o que preciso fazer antes?"
test_query "Quais os pré-requisitos de Algoritmos e Estruturas de Dados I?"
test_query "E Projeto e Análise de Algoritmos depende de quê?"
test_query "Quem leciona PAA?"

echo "╔══════════════════════════════════════════════════════╗"
echo "║  🎯 CONVERSA 3: Procurando professor                 ║"
echo "╚══════════════════════════════════════════════════════╝"
test_query "Preciso falar com o Bruno Kimura, onde encontro ele?"
test_query "Qual o email dele?"
test_query "O que ele leciona?"
test_query "Tem outros professores de Redes?"

echo "╔══════════════════════════════════════════════════════╗"
echo "║  🎯 CONVERSA 4: Dúvidas sobre regulamento            ║"
echo "╚══════════════════════════════════════════════════════╝"
test_query "Quantas horas de atividades complementares preciso?"
test_query "O que conta como atividade complementar?"
test_query "Posso usar estágio como atividade complementar?"
test_query "E monitoria conta?"

echo "╔══════════════════════════════════════════════════════╗"
echo "║  🎯 CONVERSA 5: Biomédica                            ║"
echo "╚══════════════════════════════════════════════════════╝"
test_query "Fale sobre Transdução de Grandezas Biomédicas"
test_query "Quem são os professores dessa disciplina?"
test_query "Quais os pré-requisitos?"
test_query "Tem outras disciplinas de Engenharia Biomédica?"

echo "╔══════════════════════════════════════════════════════╗"
echo "║  🎯 CONVERSA 6: Machine Learning                     ║"
echo "╚══════════════════════════════════════════════════════╝"
test_query "Quais professores trabalham com Machine Learning?"
test_query "O Marcos Quiles trabalha com o quê?"
test_query "Qual o email do Marcos Quiles?"
test_query "Tem disciplina de Redes Neurais?"

echo "╔══════════════════════════════════════════════════════╗"
echo "║  🎯 CONVERSA 7: Siglas e códigos                     ║"
echo "╚══════════════════════════════════════════════════════╝"
test_query "O que é AED I?"
test_query "E AED II?"
test_query "Qual a diferença entre POO e PAA?"
test_query "O que é SO?"

echo "╔══════════════════════════════════════════════════════╗"
echo "║  🎯 CONVERSA 8: Novas disciplinas                    ║"
echo "╚══════════════════════════════════════════════════════╝"
test_query "Fale sobre Tópicos em Tecnologia da Computação"
test_query "E Técnicas Experimentais?"
test_query "Qual a carga horária de Resolução de Problemas via Modelagem?"
test_query "Quem leciona Tópicos em Matemática Computacional?"

echo "╔══════════════════════════════════════════════════════╗"
echo "║  🎯 CONVERSA 9: Dependências                         ║"
echo "╚══════════════════════════════════════════════════════╝"
test_query "Quais disciplinas dependem de Cálculo?"
test_query "Quais disciplinas dependem de Sistemas Operacionais?"
test_query "O que preciso para cursar Redes de Computadores?"
test_query "Teoria dos Grafos depende de quê?"

echo "╔══════════════════════════════════════════════════════╗"
echo "║  🎯 CONVERSA 10: Regimento interno                   ║"
echo "╚══════════════════════════════════════════════════════╝"
test_query "O que diz o artigo 35 do regimento?"
test_query "E o artigo 10?"
test_query "Como funciona aproveitamento de disciplinas?"
test_query "O que é a Congregação?"

echo ""
echo "🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥"
echo "💥 MEGA TESTES CONCLUÍDOS! 40 PERGUNTAS! 💥"
echo "🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥"
